#Datos utilizados para rellenar información
hombres_nombres  = ['Adel', 'Adonis', 'Ajaz', 'Akos', 'Aldo', 'Amets', 'Amaro',
                    'Aquiles', 'Algimantas', 'Alpidio', 'Amrane', 'Anish', 'Arián',
                    'Ayun', 'Azariel', 'Bagrat', 'Bencomo', 'Bertino', 'Candi',
                    'Cesc', 'Cirino', 'Crisólogo', 'Cruz', 'Danilo', 'Dareck',
                    'Dariel', 'Darin', 'Delmiro', 'Damen', 'Dilan', 'Dipa',
                    'Doménico', 'Drago', 'Edivaldo', 'Elvis', 'Elyan', 'Emeric',
                    'Engracio', 'Ensa', 'Eñaut', 'Eleazar', 'Eros', 'Eufemio',
                    'Feiyang', 'Fiorenzo', 'Foudil', 'Galo', 'Gastón', 'Giulio',
                    'Gautam', 'Gentil', 'Gianni', 'Gianluca', 'Giorgio', 'Gourav',
                    'Grober', 'Guido', 'Guifre', 'Guim', 'Hermes', 'Inge', 'Irai',
                    'Iraitz', 'Iyad', 'Iyán', 'Jeremías', 'Joao', 'Jun', 'Khaled',
                    'Leónidas', 'Lier', 'Lionel', 'Lisandro', 'Lucián', 'Mael',
                    'Misael', 'Moad', 'Munir', 'Nael', 'Najim', 'Neo', 'Neil',
                    'Nikita', 'Nilo', 'Otto', 'Pep', 'Policarpo', 'Radu', 'Ramsés',
                    'Rómulo', 'Roy', 'Severo', 'Sidi', 'Simeón', 'Taha', 'Tao',
                    'Vadim', 'Vincenzo', 'Zaid', 'Zigor', 'Zouhair', 'Hugo', 'Mateo',
                    'Martín', 'Lucas', 'Leo', 'Daniel', 'Alejandro', 'Manuel',
                    'Pablo', 'Álvaro', 'Adrián', 'Enzo', 'Mario', 'Diego', 'David',
                    'Oliver', 'Marcos', 'Thiago', 'Marco', 'Álex', 'Javier', 'Izan',
                    'Bruno', 'Miguel', 'Antonio', 'Gonzalo', 'Liam', 'Gael', 'Marc',
                    'Carlos', 'Juan', 'Ángel', 'Dylan', 'Nicolás', 'José', 'Sergio',
                    'Gabriel', 'Luca', 'Jorge', 'Darío', 'Íker', 'Samuel', 'Eric',
                    'Adam', 'Héctor', 'Francisco', 'Rodrigo', 'Jesús', 'Erik', 'Amir',
                    'Jaime', 'Ian', 'Rubén', 'Aarón', 'Iván', 'Pau', 'Víctor',
                    'Guillermo', 'Luis', 'Mohamed', 'Pedro', 'Julen', 'Unai', 'Rafael',
                    'Santiago', 'Saúl', 'Alberto', 'Noah', 'Aitor', 'Joel', 'Nil', 'Jan',
                    'Pol', 'Raúl', 'Matías', 'Martí', 'Fernando', 'Andrés', 'Rayan',
                    'Alonso', 'Ismael', 'Asier', 'Biel', 'Ander', 'Aleix', 'Axel', 'Alan',
                    'Ignacio', 'Fabio', 'Neizan', 'Jon', 'Teo', 'Isaac', 'Arnau', 'Luka',
                    'Max', 'Imran', 'Youssef', 'Anas', 'Elías', 'Abaigar', 'Adei', 'Adur',
                    'Adiran', 'Aimar', 'Aitor', 'Andoni', 'Ander', 'Antxon', 'Amets',
                    'Aratz', 'Argi', 'Aritz', 'Asier', 'Balkoe', 'Baltz', 'Bazkoare',
                    'Beltso', 'Bernat', 'Beñat', 'Bikendi', 'Biktor', 'Bizen', 'Dabi',
                    'Dari', 'Damen', 'Diagur', 'Dunixi', 'Eako', 'Eder', 'Edorta',
                    'Edur', 'Eki', 'Ekaitz', 'Eladi', 'Elixi', 'Eloi', 'Emiri', 'Eneko',
                    'Endrike', 'Eritz', 'Etor', 'Euken', 'Ferran', 'Frantzisko', 'Ganiz',
                    'Gari', 'Gentzen', 'Gergori', 'Gilem', 'Gizon', 'Goiznabar',
                    'Gontzal', 'Gorka', 'Grazian', 'Guren', 'Haize', 'Haran', 'Haritz',
                    'Heiko', 'Hodei', 'Ibai', 'Ibar', 'Igon', 'Igor', 'Iker', 'Imanol',
                    'Iñaki', 'Ipar', 'Irai', 'Iren', 'Izan', 'Izei', 'Jon', 'Jeino',
                    'Joritz', 'Josu', 'Julen', 'Jurgi', 'Kai', 'Kasi', 'Kauldi', 'Kutun',
                    'Lain', 'Luken', 'Maide', 'Mairu', 'Maren', 'Markel', 'Martitz',
                    'Mikel', 'Negu', 'Neketi', 'Nikanor', 'Odei', 'Oier', 'Oihan',
                    'Orentzi', 'Orixe', 'Ortzadar', 'Ostertz', 'Paken', 'Patxi', 'Roke',
                    'Sanduru', 'Semenko', 'Sendoa', 'Silban', 'Sukil', 'Todor', 'Txarles',
                    'Ugutz', 'Uhaitz', 'Unai', 'Untzalu', 'Urtzi', 'Uztai', 'Xabier',
                    'Zuhaitz', 'Zuri', 'Zuzen', 'Adolf', 'Adrià', 'Agustí', 'Alberic',
                    'Aleix', 'Àlvar', 'Amadeu', 'Andreu', 'Aran', 'Ariel', 'Arnald',
                    'Arnau', 'Artur', 'Bernabe', 'Bernat', 'Biel', 'Blai', 'Carles',
                    'Cesc', 'Climen', 'Constantí', 'Cosme', 'Cristòfol', 'Domènech',
                    'Doroteu', 'Eduard', 'Elies', 'Eloi', 'Elpidi', 'Enric', 'Ernest',
                    'Estanislau', 'Esteve', 'Eugeni', 'Eusevi', 'Feliu', 'Ferran',
                    'Ferrer', 'Fredreric', 'Genari', 'Gener', 'Genis', 'Gonçal', 'Guifré',
                    'Guillem', 'Guiu', 'Honorat', 'Hospici', 'Ignasi', 'Isidre', 'Jacint',
                    'Jan', 'Jaume', 'Joaquín', 'Jonatan', 'Jordi', 'Leopold', 'Lluc',
                    'Marc', 'Marcel', 'Martí', 'Mateu', 'Maurici', 'Màxim', 'Medir',
                    'Moisès', 'Nadal', 'Nicolau', 'Nil', 'Oriol', 'Osvald', 'Ovidi',
                    'Pacomi', 'Pelai', 'Pere', 'Pol', 'Prosper', 'Rafel', 'Raimon',
                    'Raül', 'Ricard', 'Robert', 'Roc', 'Roderic', 'Roger', 'Sanc',
                    'Sàndal', 'Serni', 'Simó', 'Thiago', 'Valentí', 'Vicenç', 'Víctor',
                    'Virgili', 'Xavi', 'Xavier', 'Zoel', 'Agostiño', 'Airas', 'Alberte',
                    'Aleixo', 'Aldán', 'Alexandre', 'Amaro', 'Amil', 'André', 'Anselmo',
                    'Antón', 'Antoín', 'Antoíño', 'Ánxelo', 'Anxo', 'Anxos', 'Artai',
                    'Artur', 'Arximiro', 'Aurelio', 'Basilio', 'Benedito', 'Bento',
                    'Benvito', 'Benxamín', 'Bernal', 'Bernaldo', 'Bernardiño', 'Bieito',
                    'Boaventura', 'Brais', 'Breixo', 'Breogán', 'Brigo', 'Bruno',
                    'Caetano', 'Calisto', 'Calros', 'Camilo', 'Cibrán', 'Cilistro',
                    'Ciriaco', 'Clemenzo', 'Clodio', 'Cosme', 'Cristovo', 'Davide',
                    'Diogo', 'Domingos', 'Duarte', 'Eloy', 'Estevo', 'Euloxio', 'Eutelo',
                    'Euxenio', 'Exidio', 'Fernán', 'Fidel', 'Filipe', 'Firmino', 'Fiz',
                    'Frederico', 'Froitoso', 'Gasparo', 'Goio', 'Hixinio', 'Iago',
                    'Lois', 'Luar', 'Luís', 'Manoel', 'Martiño', 'Odón', 'Pascoal',
                    'Payo', 'Peio', 'Pello', 'Peru', 'Quentin', 'Roi', 'Roxelio', 'Rui',
                    'Tadeu', 'Uxío', 'Vicenzo', 'Virxilio', 'Xabier', 'Xacinto',
                    'Xacobe', 'Xacobo', 'Xaime', 'Xan', 'Xandro', 'Xaneiro', 'Xandre',
                    'Xaquin', 'Xenaro', 'Xeraldo', 'Xerardo', 'Xermán', 'Xesus', 'Xián',
                    'Xoán', 'Xoel', 'Xorxe', 'Xosé', 'Xurxo']
                    
mujeres_nombres  = ['Adara', 'Agata', 'Agripina', 'Ainhara', 'Aixa', 'Alegría',
                    'Alia', 'Alla', 'América', 'Aminata', 'Amor', 'Anahí', 'Ania',
                    'Aquilina', 'Ariadne', 'Arya', 'Asia', 'Atenea', 'Bella',
                    'Benilde', 'Camino', 'Carmina', 'Casandra', 'Celina', 'Chaymae',
                    'Clemencia', 'Cora', 'Cruz', 'Custodia', 'Dalila', 'Danae',
                    'Dania', 'Demetria', 'Denise', 'Doina', 'Dominica', 'Dorina',
                    'Doris', 'Duna', 'Elaia', 'Elida', 'Enma', 'Erundina', 'Etelvina',
                    'Evelia', 'Evelin', 'Fatma', 'Federica', 'Flavia', 'Florina',
                    'Gadea', 'Griselda', 'Guacimara', 'Guiomar', 'Hasna', 'Indara',
                    'Inna', 'Iraide', 'Irantzu', 'Ivette', 'Jade', 'Johana', 'Juncal',
                    'Kira', 'Larisa', 'Laureana', 'Leia', 'Lena', 'Leocadia', 'Libe',
                    'Lilia', 'Linda', 'Lisa', 'Liudmila', 'Livia', 'Lluna', 'Luana',
                    'Lucinda', 'Mabel', 'Manar', 'Mariama', 'Marianela', 'Nadine',
                    'Naila', 'Nawal', 'Nazareth', 'Nelly', 'Noah', 'Norah', 'Penélope',
                    'Remei', 'Rosalba', 'Sabah', 'Safia', 'Saliha', 'Saloua', 'Sana',
                    'Sanaa', 'Severina', 'Silvina', 'Talia', 'Tasnim', 'Telma', 'Valle',
                    'Ximena', 'Xiomara', 'Yadira', 'Yamila', 'Yesenia', 'Yuliya',
                    'Yumara', 'Zakia', 'Lucía', 'Sofía', 'Martina', 'María', 'Julia',
                    'Paula', 'Valeria', 'Emma', 'Daniela', 'Carla', 'Alba', 'Noa',
                    'Alma', 'Sara', 'Carmen', 'Vega', 'Lara', 'Mia', 'Valentina',
                    'Olivia', 'Claudia', 'Jimena', 'Lola', 'Chloe', 'Aitana', 'Abril',
                    'Ana', 'Laia', 'Triana', 'Candela', 'Alejandra', 'Elena', 'Vera',
                    'Manuela', 'Adriana', 'Inés', 'Marta', 'Carlota', 'Irene',
                    'Victoria', 'Blanca', 'Marina', 'Laura', 'Rocío', 'Alicia',
                    'Clara', 'Nora', 'Lia', 'Ariadna', 'Zoe', 'Amira', 'Gala', 'Celia',
                    'Leire', 'Eva', 'Ángela', 'Andrea', 'África', 'Luna', 'Ainhoa',
                    'Ainara', 'India', 'Nerea', 'Ona', 'Elsa', 'Isabel', 'Leyre',
                    'Gabriela', 'Aina', 'Cayetana', 'Iria', 'Jana', 'Mar', 'Cloe',
                    'Lina', 'Julieta', 'Adara', 'Naia', 'Iris', 'Nour', 'Mara',
                    'Helena', 'Yasmín', 'Natalia', 'Arlet', 'Diana', 'Aroa', 'Amaia',
                    'Cristina', 'Nahia', 'Isabella', 'Malak', 'Elia', 'Carolina',
                    'Berta', 'Fátima', 'Nuria', 'Azahara', 'Macarena', 'Aurora',
                    'Abantza', 'Abarne', 'Abesti', 'Adartza', 'Adirane', 'Agara',
                    'Agata', 'Agate', 'Aimara', 'Ainara', 'Aines', 'Ainhoa', 'Aintza',
                    'Aintzane.', 'Alaia', 'Alaikari', 'Alaiñe', 'Albane', 'Alda',
                    'Aliza', 'Alize', 'Alode', 'Alodi', 'Aloise', 'Amade', 'Amaia',
                    'Amane', 'Amele', 'Andoitza', 'Ane', 'Antia', 'Anuntxi', 'Arantxa',
                    'Arantza', 'Arene', 'Aretxa', 'Argia', 'Astere', 'Begoña',
                    'Dogartze', 'Domeka', 'Dunixe', 'Ederne', 'Edurne', 'Egia',
                    'Ekaitza', 'Elaia', 'Elaia', 'Elixe', 'Enara', 'Estibaliz',
                    'Eulari', 'Eztia', 'Florentzi', 'Gadea', 'Garaine', 'Gorane',
                    'Gure', 'Haizea', 'Haizeder', 'Hegoa', 'Ibarne', 'Ikerne',
                    'Ilargi', 'Iluntze', 'Iraide', 'Irune', 'Izadi', 'Jaione',
                    'Julene', 'Kaia', 'Kaiene', 'Keltse', 'Kemena', 'Laia', 'Leire',
                    'Letizia', 'Lide', 'Loredi', 'Lukene', 'Lutxi', 'Luzia', 'Maia',
                    'Maitane', 'Maite', 'Malen', 'Markele', 'Mikela', 'Milia',
                    'Mirari', 'Nagore', 'Nahia', 'Nahikari', 'Naiara', 'Naroa',
                    'Nekane', 'Nerea', 'Oihana', 'Oihane', 'Olaia', 'Paule',
                    'Polentze', 'Sabiñe', 'Santsa', 'Sarabe', 'Sua', 'Tala',
                    'Taresa', 'Uda', 'Udane', 'Udara', 'Ula', 'Urzuri', 'Yera',
                    'Zeiane', 'Zohardi', 'Zorione', 'Zumaia', 'Zuria', 'Zuzene',
                    'Abellera', 'Agnès', 'Aida', 'Aïna', 'Aisha', 'Aixa', 'Albà',
                    'Alix', 'Alma', 'Aloma', 'Anaïs', 'Àngels', 'Anna', 'Ares',
                    'Ariadna', 'Arlet', 'Aura', 'Bet', 'Beth', 'Blau', 'Cel',
                    'Cèlia', 'Chloé', 'Cira', 'Clàudia', 'Cloè', 'Consol', 'Cora',
                    'Dàlia', 'Dèlia', 'Dolça', 'Duna', 'Dúnia', 'Edna', 'Elna',
                    'Elsa', 'Emma', 'Estel', 'Etna', 'Finestres', 'Francina',
                    'Gemma', 'Gina', 'Iria', 'Ivet', 'Jana', 'Joana', 'Judit',
                    'Júlia', 'Laia', 'Lara', 'Lea', 'Lena', 'Lia', 'Lis', 'Llora',
                    'Llúcia', 'Margarida', 'Meritxell', 'Mireia', 'Montserrat',
                    'Nàdia', 'Nara', 'Neus', 'Nina', 'Nit', 'Noa', 'Nora', 'Nura',
                    'Núria', 'Ona', 'Queralt', 'Ramona', 'Remei', 'Rita', 'Roser',
                    'Sança', 'Sira', 'Socors', 'Sol', 'Soledat', 'Thaís', 'Txell',
                    'Vera', 'Vinyet', 'Xènia', 'Zoa', 'Ádega', 'Agostiña', 'Áine',
                    'Alana', 'Alborada', 'Albura', 'Alda', 'Aldana', 'Alexandra',
                    'Alexia', 'Alla', 'Alodia', 'Aloia', 'Amaina', 'Amil', 'Antela',
                    'Antía', 'Antoniña', 'Anxa', 'Ánxela', 'Ánxeles', 'Anxélica',
                    'Anxos', 'Apana', 'Aranza', 'Aránzazu', 'Arduína', 'Arxentina',
                    'Asunta', 'Aunia', 'Baia', 'Balla', 'Beata', 'Bélxica', 'Benvida',
                    'Benxamina', 'Branca', 'Brenda', 'Briana', 'Brianda', 'Brisda',
                    'Bríxida', 'Camiño', 'Candea', 'Candeloria', 'Catuxa', 'Cebreiro',
                    'Cecía', 'Cela', 'Celina', 'Celtia', 'Chorima', 'Cía', 'Cilla',
                    'Doa', 'Dubra', 'Einés', 'Elba', 'Elvia', 'Erea', 'Euxea',
                    'Euxenia', 'Evelina', 'Exeria', 'Franqueira', 'Fulxencia',
                    'Glenda', 'Hixinia', 'Icía', 'Ifixenia', 'Ilduara', 'Iria',
                    'Iría', 'Irimia', 'Lana', 'Loucia', 'Malvina', 'Maxina',
                    'Mencía', 'Minia', 'Moira', 'Mor', 'Muma', 'Muriel', 'Navia',
                    'Noela', 'Noreia', 'Roxelia', 'Roxeria', 'Sabela', 'Sarela',
                    'Tareixa', 'Ulla', 'Uxía', 'Virxilia', 'Xacinta', 'Xandra',
                    'Xaquelina', 'Xasmín', 'Xela', 'Xeloíra', 'Xema', 'Xenevra',
                    'Xenia', 'Xenoveva', 'Xenxa', 'Xiana', 'Xilda', 'Xosefa',
                    'Xudite', 'Xulia', 'Xulieta', 'Xunqueira', 'Xuventina', 'Zeltia']

apellidos        = ['González', 'Muñoz', 'Rojas', 'Díaz', 'Pérez', 'Soto',
                    'Contreras', 'Silva', 'Martínez', 'Sepúlveda', 'Morales',
                    'Rodríguez', 'López', 'Fuentes', 'Hernández', 'Torres', 'Araya',
                    'Flores', 'Espinoza', 'Valenzuela', 'Castillo', 'Tapia', 'Reyes',
                    'Gutiérrez', 'Castro', 'Pizarro', 'Álvarez', 'Vásquez', 'Sánchez',
                    'Fernández', 'Ramírez', 'Carrasco', 'Gómez', 'Cortés', 'Herrera',
                    'Núñez', 'Jara', 'Vergara', 'Rivera', 'Figueroa', 'Riquelme',
                    'García', 'Miranda', 'Bravo', 'Vera', 'Molina', 'Vega', 'Campos',
                    'Sandoval', 'Orellana', 'Cárdenas', 'Olivares', 'Alarcón',
                    'Gallardo', 'Ortiz', 'Garrido', 'Salazar', 'Guzmán', 'Henríquez',
                    'Saavedra', 'Navarro', 'Aguilera', 'Parra', 'Romero', 'Aravena',
                    'Vargas', 'Vázquez', 'Cáceres', 'Yáñez', 'Leiva', 'Escobar',
                    'Ruiz', 'Valdés', 'Vidal', 'Salinas', 'Zúñiga', 'Peña', 'Godoy',
                    'Lagos', 'Maldonado', 'Bustos', 'Medina', 'Pino', 'Palma',
                    'Moreno', 'Sanhueza', 'Carvajal', 'Navarrete', 'Sáez', 'Alvarado',
                    'Donoso', 'Poblete', 'Bustamante', 'Toro', 'Ortega', 'Venegas',
                    'Lopez', 'Mendoza', 'Farías', 'San Martín', 'Lucero', 'Sosa',
                    'Quiroga', 'Jiménez', 'Mora', 'Calderón', 'Martín', 'Alonso',
                    'Domínguez', 'Ramos']

#Comuna, Ciudad, Región, Provincia, Probabilidad (Basada en el CENSO del año 2017)
localizacion = [['Puente Alto', 'Puente Alto', 'Metropolitana de Santiago', 'Cordillera', 3.765] ,
                ['Maipú', 'Maipú', 'Metropolitana de Santiago', 'Santiago', 3.422] ,
                ['Santiago', 'Santiago', 'Metropolitana de Santiago', 'Santiago', 3.271] ,
                ['La Florida', 'Santiago', 'Metropolitana de Santiago', 'Santiago', 2.403] ,
                ['Antofagasta', 'Antofagasta', 'Antofagasta', 'Antofagasta', 2.286] ,
                ['Viña del Mar', 'Viña del Mar', 'Valparaíso', 'Valparaíso', 2.183] ,
                ['San Bernardo', 'San Bernardo', 'Metropolitana de Santiago', 'Maipo', 1.976] ,
                ['Valparaíso', 'Valparaíso', 'Valparaíso', 'Valparaíso', 1.945] ,
                ['Las Condes', 'Las Condes', 'Metropolitana de Santiago', 'Santiago', 1.934] ,
                ['Temuco', 'Temuco', 'La Araucanía', 'Cautín', 1.852] ,
                ['Peñalolén', 'Peñalolen', 'Metropolitana de Santiago', 'Santiago', 1.583] ,
                ['Rancagua', 'Rancagua', "Libertador General Bernardo O'Higgins", 'Cachapoal', 1.518] ,
                ['Arica', 'Arica', 'Arica y Parinacota', 'Arica', 1.452] ,
                ['Concepción', 'Concepción', 'Biobío', 'Concepción', 1.448] ,
                ['Quilicura', 'Quilicura', 'Metropolitana de Santiago', 'Santiago', 1.375] ,
                ['Ñuñoa', 'Ñuñoa', 'Metropolitana de Santiago', 'Santiago', 1.365] ,
                ['Talca', 'Talca', 'Maule', 'Talca', 1.352] ,
                ['Pudahuel', 'Pudahuel', 'Metropolitana de Santiago', 'Santiago', 1.348] ,
                ['Coquimbo', 'La Serena', 'Coquimbo', 'Elqui', 1.339] ,
                ['La Serena', 'La Serena', 'Coquimbo', 'Elqui', 1.45] ,
                ['Iquique', 'Iquique', 'Tarapacá', 'Iquique', 1.233] ,
                ['La Pintana', 'La Pintana', 'Metropolitana de Santiago', 'Santiago', 1.155] ,
                ['Puerto Montt', 'Puerto Montt', 'Los Lagos', 'Llanquihue', 1.613] ,
                ['Chillán', 'Chillán', 'Ñuble', 'Diguillín', 1.078] ,
                ['El Bosque', 'El Bosque', 'Metropolitana de Santiago', 'Santiago', 1.065] ,
                ['Calama', 'Calama', 'Antofagasta', 'El Loa', 1.034] ,
                ['Recoleta', 'Recoleta', 'Metropolitana de Santiago', 'Santiago', 1.034] ,
                ['Copiapó', 'Copiapó', 'Atacama', 'Copiapó', 0.989] ,
                ['Valdivia', 'Valdivia', 'Los Ríos', 'Valdivia', 1.05] ,
                ['Quilpué', 'Quilpue', 'Valparaíso', 'Marga Marga', 0.971] ,
                ['Talcahuano', 'Talcahuano', 'Biobío', 'Concepción', 0.97] ,
                ['Osorno', 'Osorno', 'Los Lagos', 'Osorno', 0.969] ,
                ['Renca', 'Renca', 'Metropolitana de Santiago', 'Santiago', 0.964] ,
                ['Providencia', 'Providencia', 'Metropolitana de Santiago', 'Santiago', 0.931] ,
                ['Estación Central', 'Estación Central', 'Metropolitana de Santiago', 'Santiago', 0.924] ,
                ['Cerro Navia', 'Cerro Navia', 'Metropolitana de Santiago', 'Santiago', 0.868] ,
                ['San Pedro de la Paz', 'San Pedro de la Paz', 'Biobío', 'Concepción', 0.863] ,
                ['Conchalí', 'Conchali', 'Metropolitana de Santiago', 'Santiago', 0.832] ,
                ['Curicó', 'Curicó', 'Maule', 'Curicó', 0.822] ,
                ['Villa Alemana', 'Villa Alemana', 'Valparaíso', 'Marga Marga', 0.821] ,
                ['Punta Arenas', 'Punta Arenas', 'Magallanes y de la Antártica Chilena', 'Magallanes', 0.809] ,
                ['La Granja', 'La Granja', 'Metropolitana de Santiago', 'Santiago', 0.763] ,
                ['Macul', 'Macul', 'Metropolitana de Santiago', 'Santiago', 0.763] ,
                ['Coronel', 'Coronel', 'Biobío', 'Concepción', 0.735] ,
                ['Quinta Normal', 'Quinta Normal', 'Metropolitana de Santiago', 'Santiago', 0.72] ,
                ['San Miguel', 'San Miguel', 'Metropolitana de Santiago', 'Santiago', 0.707] ,
                ['Alto Hospicio', 'Alto Hospicio', 'Tarapacá', 'Iquique', 0.689] ,
                ['Lo Barnechea', 'Lo Barnechea', 'Metropolitana de Santiago', 'Santiago', 0.676] ,
                ['Pedro Aguirre Cerda', 'Pedro Aguirre Cerda', 'Metropolitana de Santiago', 'Santiago', 0.663] ,
                ['Independencia', 'Independencia', 'Metropolitana de Santiago', 'Santiago', 0.656] ,
                ['Lo Espejo', 'Lo Espejo', 'Metropolitana de Santiago', 'Santiago', 0.647] ,
                ['Huechuraba', 'Huechuraba', 'Metropolitana de Santiago', 'Santiago', 0.646] ,
                ['Lo Prado', 'Lo Prado', 'Metropolitana de Santiago', 'Santiago', 0.629] ,
                ['San Joaquín', 'San Joaquín', 'Metropolitana de Santiago', 'Santiago', 0.619] ,
                ['La Reina', 'La Reina', 'Metropolitana de Santiago', 'Santiago', 0.608] ,
                ['Hualpén', 'Hualpen', 'Biobío', 'Concepción', 0.595] ,
                ['La Cisterna', 'La Cisterna', 'Metropolitana de Santiago', 'Santiago', 0.59] ,
                ['Colina', 'Colina', 'Metropolitana de Santiago', 'Chacabuco', 0.583] ,
                ['San Antonio', 'San Antonio', 'Valparaíso', 'San Antonio', 0.566] ,
                ['Chiguayante', 'Chiguayante', 'Biobío', 'Concepción', 0.562] ,
                ['Vitacura', 'Vitacura', 'Metropolitana de Santiago', 'Santiago', 0.56] ,
                ['Peñaflor', 'Peñaflor', 'Metropolitana de Santiago', 'Talagante', 0.544] ,
                ['San Ramón', 'San Ramon', 'Metropolitana de Santiago', 'Santiago', 0.542] ,
                ['Cerrillos', 'Cerrillos', 'Metropolitana de Santiago', 'Santiago', 0.529] ,
                ['Ovalle', 'Ovalle', 'Coquimbo', 'Limarí', 0.498] ,
                ['Linares', 'Linares', 'Maule', 'Linares', 0.483] ,
                ['Quillota', 'Quillota', 'Valparaíso', 'Quillota', 0.481] ,
                ['Melipilla', 'Melipilla', 'Metropolitana de Santiago', 'Melipilla', 0.474] ,
                ['Buin', 'Buin', 'Metropolitana de Santiago', 'Maipo', 0.43] ,
                ['San Felipe', 'San Felipe', 'Valparaíso', 'San Felipe de Aconcagua', 0.421] ,
                ['Los Andes', 'Los Andes', 'Valparaíso', 'Los Andes', 0.39] ,
                ['San Fernando', 'San Fernando', "Libertador General Bernardo O'Higgins", 'Colchagua', 0.383] ,
                ['Talagante', 'Talagante', 'Metropolitana de Santiago', 'Talagante', 0.373] ,
                ['Cauquenes', 'Cauquenes', 'Maule', 'Cauquenes', 0.331] ,
                ['Coyhaique', 'Coyhaique', 'Aysén del General Carlos Ibáñez del Campo', 'Coyhaique', 0.326] ,
                ['Machalí', 'Machali', "Libertador General Bernardo O'Higgins", 'Cachapoal', 0.319] ,
                ['Angol', 'Angol', 'La Araucanía', 'Malleco', 0.319] ,
                ['La Calera', 'La Calera', 'Valparaíso', 'Quillota', 0.309] ,
                ['Penco', 'Penco', 'Biobío', 'Concepción', 0.306] ,
                ['Vallenar', 'Vallenar', 'Atacama', 'Huasco', 0.297] ,
                ['Lota', 'Lota', 'Biobío', 'Concepción', 0.284] ,
                ['Tomé', 'Tome', 'Biobío', 'Concepción', 0.278] ,
                ['Puerto Montt', 'Alerce', 'Los Lagos', 'Llanquihue', 0.277] ,
                ['Padre Las Casas', 'Padre las Casas', 'La Araucanía', 'Cautín', 0.276] ,
                ['Concón', 'Concon', 'Valparaíso', 'Valparaíso', 0.258] ,
                ['Valparaíso', 'Placilla de Peñuelas', 'Valparaíso', 'Valparaíso', 0.258] ,
                ['Limache', 'Limache', 'Valparaíso', 'Marga Marga', 0.256] ,
                ['Rengo', 'Rengo', "Libertador General Bernardo O'Higgins", 'Cachapoal', 0.247] ,
                ['Lampa', 'Lampa', 'Metropolitana de Santiago', 'Chacabuco', 0.247] ,
                ['Molina', 'Molina', 'Maule', 'Curicó', 0.244] ,
                ['Constitución', 'Constitución', 'Maule', 'Talca', 0.223] ,
                ['Castro', 'Castro', 'Los Lagos', 'Chiloé', 0.219] ,
                ['San Carlos', 'San Carlos', 'Ñuble', 'Punilla', 0.213] ,
                ['Villarrica', 'Villarrica', 'La Araucanía', 'Cautín', 0.208] ,
                ['Paine', 'Paine', 'Metropolitana de Santiago', 'Maipo', 0.205] ,
                ['Parral', 'Parral', 'Maule', 'Linares', 0.202] ,
                ['Maule', 'Culenar', 'Maule', 'Talca', 0.199] ,
                ['Curanilahue', 'Curanilahue', 'Biobío', 'Arauco', 0.198] ,
                ['El Monte', 'El Monte', 'Metropolitana de Santiago', 'Talagante', 0.0] ,
                ['San Javier', 'San Javier', 'Maule', 'Linares', 0.19] ,
                ['Graneros', 'Graneros', "Libertador General Bernardo O'Higgins", 'Cachapoal', 0.188] ,
                ['Ancud', 'Ancud', 'Los Lagos', 'Chiloé', 0.185] ,
                ['Chillán Viejo', 'Chillán Viejo', 'Ñuble', 'Diguillín', 0.179] ,
                ['La Unión', 'La Unión', 'Los Ríos', 'Ranco', 0.174] ,
                ['Quintero', 'Quintero', 'Valparaíso', 'Valparaíso', 0.172] ,
                ['Puerto Varas', 'Puerto Varas', 'Los Lagos', 'Llanquihue', 0.172] ,
                ['Victoria', 'Victoria', 'La Araucanía', 'Malleco', 0.162] ,
                ['Tocopilla', 'Tocopilla', 'Antofagasta', 'Tocopilla', 0.161] ,
                ['Lautaro', 'Lautaro', 'La Araucanía', 'Cautín', 0.159] ,
                ['Mulchén', 'Mulchén', 'Biobío', 'Biobío', 0.158] ,
                ['Temuco', 'Labranza', 'La Araucanía', 'Cautín', 0.157] ,
                ['Nacimiento', 'Nacimiento', 'Biobío', 'Biobío', 0.15] ,
                ['Santa Cruz', 'Santa Cruz', "Libertador General Bernardo O'Higgins", 'Colchagua', 0.149] ,
                ['Lebu', 'Lebu', 'Biobío', 'Arauco', 0.137] ,
                ['San Vicente de Tagua Tagua', 'San Vicente de tagua tagua', "Libertador General Bernardo O'Higgins", 'Cachapoal', 0.137] ,
                ['Cartagena', 'Cartagena', 'Valparaíso', 'San Antonio', 0.136] ,
                ['Illapel', 'Illapel', 'Coquimbo', 'Choapa', 0.136] ,
                ['San Clemente', 'San Clemente', 'Maule', 'Talca', 0.133] ,
                ['Hualqui', 'Hualqui', 'Biobío', 'Concepción', 0.129] ,
                ['La Cruz', 'La Cruz', 'Valparaíso', 'Quillota', 0.127] ,
                ['Cañete', 'Cañete', 'Biobío', 'Arauco', 0.127] ,
                ['La Ligua', 'La Ligua', 'Valparaíso', 'Petorca', 0.125] ,
                ['Puerto Natales', 'Puerto Natales', 'Magallanes y de la Antártica Chilena', 'Última Esperanza', 0.125] ,
                ['Nueva Imperial', 'Nueva Imperial', 'La Araucanía', 'Cautín', 0.123] ,
                ['Curacaví', 'Curacaví', 'Metropolitana de Santiago', 'Melipilla', 0.123] ,
                ['Casablanca', 'Casablanca', 'Valparaíso', 'Valparaíso', 0.118] ,
                ['Llaillay', 'Llaillay', 'Valparaíso', 'San Felipe de Aconcagua', 0.118] ,
                ['Arauco', 'Arauco', 'Biobío', 'Arauco', 0.115] ,
                ['Quellón', 'Quellón', 'Los Lagos', 'Chiloé', 0.115] ,
                ['Pucón', 'Pucón', 'La Araucanía', 'Cautín', 0.115] ,
                ['Puerto Aysén', 'Puerto Aysen', 'Aysén del General Carlos Ibáñez del Campo', 'Aysén', 0.114] ,
                ['Lampa', 'Valle grande', 'Metropolitana de Santiago', 'Chacabuco', 0.111] ,
                ['Río Bueno', 'Río Bueno', 'Los Ríos', 'Ranco', 0.111] ,
                ['Chimbarongo', 'Chimbarongo', "Libertador General Bernardo O'Higgins", 'Colchagua', 0.11] ,
                ['Lampa', 'Batuco', 'Metropolitana de Santiago', 'Chacabuco', 0.11] ,
                ['Pitrufquén', 'Pitrufquén', 'La Araucanía', 'Cautín', 0.108] ,
                ['Collipulli', 'Collipulli', 'La Araucanía', 'Malleco', 0.106] ,
                ['Laja', 'La Laja', 'Biobío', 'Biobío', 0.106] ,
                ['Calbuco', 'Calbuco', 'Los Lagos', 'Llanquihue', 0.104] ,
                ['Vicuña', 'Vicuña', 'Coquimbo', 'Elqui', 0.104] ,
                ['Caldera', 'Caldera', 'Atacama', 'Copiapó', 0.102] ,
                ['Loncoche', 'Loncoche', 'La Araucanía', 'Cautín', 0.1] ,
                ['Los Álamos', 'Los Álamos', 'Biobío', 'Arauco', 0.1] ,
                ['Cabrero', 'Cabrero', 'Biobío', 'Biobío', 0.098] ,
                ['El Quisco', 'El Quisco', 'Valparaíso', 'San Antonio', 0.097] ,
                ['Traiguén', 'Traiguén', 'La Araucanía', 'Malleco', 0.094] ,
                ['Isla de Maipo', 'Isla de Maipo', 'Metropolitana de Santiago', 'Talagante', 0.093] ,
                ['Los Vilos', 'Los Vilos', 'Coquimbo', 'Choapa', 0.091] ,
                ['Salamanca', 'Salamanca', 'Coquimbo', 'Choapa', 0.089] ,
                ['Llanquihue', 'Llanquihue', 'Los Lagos', 'Llanquihue', 0.085] ,
                ['Frutillar', 'Frutillar', 'Los Lagos', 'Llanquihue', 0.084] ,
                ['Mejillones', 'Mejillones', 'Antofagasta', 'Antofagasta', 0.084] ,
                ['Pichilemu', 'Pichilemu', "Libertador General Bernardo O'Higgins", 'Cardenal Caro', 0.084] ,
                ['Mostazal', 'San Francisco de Mostazal', "Libertador General Bernardo O'Higgins", 'Cachapoal', 0.083] ,
                ['Curacautín', 'Curacautín', 'La Araucanía', 'Malleco', 0.083] ,
                ['Purranque', 'Purranque', 'Los Lagos', 'Osorno', 0.083] ,
                ['Olmué', 'Olmué', 'Valparaíso', 'Marga Marga', 0.079] ,
                ['Pudahuel', 'Ciudad de los Valles', 'Metropolitana de Santiago', 'Santiago', 1.511] ,
                ['Isla de Maipo', 'La islita', 'Metropolitana de Santiago', 'Talagante', 0.075] ,
                ['Carahue', 'Carahue', 'La Araucanía', 'Cautín', 0.074] ,
                ['Paillaco', 'Paillaco', 'Los Ríos', 'Valdivia', 0.074] ,
                ['Panguipulli', 'Panguipulli', 'Los Ríos', 'Valdivia', 0.073] ,
                ['Chañaral', 'Chañaral', 'Atacama', 'Chañaral', 0.073] ,
                ['Bulnes', 'Bulnes', 'Ñuble', 'Diguillín', 0.073] ,
                ['Colina', 'Chicureo', 'Metropolitana de Santiago', 'Chacabuco', 1.183] ,
                ['Taltal', 'Taltal', 'Antofagasta', 'Antofagasta', 0.072] ,
                ['Cabildo', 'Cabildo', 'Valparaíso', 'Petorca', 0.072] ,
                ['Yungay', 'Yungay', 'Ñuble', 'Diguillín', 0.071] ,
                ['Requínoa', 'Requínoa', "Libertador General Bernardo O'Higgins", 'Cachapoal', 0.069] ,
                ['Coelemu', 'Coelemu', 'Ñuble', 'Itata', 0.068] ,
                ['San Esteban', 'San Esteban', 'Valparaíso', 'Los Andes', 0.068] ,
                ['Quillón', 'Quillón', 'Ñuble', 'Diguillín', 0.067] ,
                ['Andacollo', 'Andacollo', 'Coquimbo', 'Elqui', 0.066] ,
                ['Tierra Amarilla', 'Tierra Amarilla', 'Atacama', 'Copiapó', 0.065] ,
                ['Nogales', 'El Melón', 'Valparaíso', 'Quillota', 0.064] ,
                ['Mariquina', 'San jose de la Mariquina', 'Los Ríos', 'Valdivia', 0.064] ,
                ['Yumbel', 'Yumbel', 'Biobío', 'Biobío', 0.064] ,
                ['Los Lagos', 'Los Lagos', 'Los Ríos', 'Valdivia', 0.064] ,
                ['Calle Larga', 'Calle Larga', 'Valparaíso', 'Los Andes', 0.063] ,
                ['Santa Juana', 'Santa Juana', 'Biobío', 'Concepción', 0.063] ,
                ['Teno', 'Teno', 'Maule', 'Curicó', 0.062] ,
                ['Quirihue', 'Quirihue', 'Ñuble', 'Itata', 0.062] ,
                ['Hijuelas', 'Hijuelas', 'Valparaíso', 'Quillota', 0.062] ,
                ['Pozo Almonte', 'Pozo Almonte', 'Tarapacá', 'Tamarugal', 0.061] ,
                ['Coihueco', 'Coihueco', 'Ñuble', 'Punilla', 0.06] ,
                ['Algarrobo', 'Algarrobo', 'Valparaíso', 'San Antonio', 0.059] ,
                ['Doñihue', 'Lo Miranda', "Libertador General Bernardo O'Higgins", 'Cachapoal', 0.059] ,
                ['Nogales', 'Nogales', 'Valparaíso', 'Quillota', 0.058] ,
                ['Pirque', 'El Principal', 'Metropolitana de Santiago', 'Cordillera', 0.058] ,
                ['Nancagua', 'Nancagua', "Libertador General Bernardo O'Higgins", 'Colchagua', 0.058] ,
                ['Gorbea', 'Gorbea', 'La Araucanía', 'Cautín', 0.056] ,
                ['Peumo', 'Peumo', "Libertador General Bernardo O'Higgins", 'Cachapoal', 0.056] ,
                ['Lanco', 'Lanco', 'Los Ríos', 'Valdivia', 0.056] ,
                ['Puchuncaví', 'Las Ventanas', 'Valparaíso', 'Valparaíso', 0.055] ,
                ['Villa Alegre', 'Villa Alegre', 'Maule', 'Linares', 0.054] ,
                ['Rinconada', 'Rinconada', 'Valparaíso', 'Los Andes', 0.053] ,
                ['Santa Bárbara', 'Santa Bárbara', 'Biobío', 'Biobío', 0.052] ,
                ['Los Muermos', 'Los Muermos', 'Los Lagos', 'Llanquihue', 0.052] ,
                ['Calera de Tango', 'Calera de Tango', 'Metropolitana de Santiago', 'Maipo', 0.051] ,
                ['Tucapel', 'Huépil', 'Biobío', 'Biobío', 0.051] ,
                ['Catemu', 'Catemu', 'Valparaíso', 'San Felipe de Aconcagua', 0.051] ,
                ['Las Cabras', 'Las Cabras', "Libertador General Bernardo O'Higgins", 'Cachapoal', 0.051] ,
                ['Colina', 'Chamisero', 'Metropolitana de Santiago', 'Chacabuco', 0.051] ,
                ['Santa María', 'Santa María', 'Valparaíso', 'San Felipe de Aconcagua', 0.05] ,
                ['Purén', 'Purén', 'La Araucanía', 'Malleco', 0.049] ,
                ['Doñihue', 'Doñihue', "Libertador General Bernardo O'Higgins", 'Cachapoal', 0.049] ,
                ['Fresia', 'Fresia', 'Los Lagos', 'Llanquihue', 0.048] ,
                ['Diego de Almagro', 'Diego de Almagro', 'Atacama', 'Chañaral', 0.047] ,
                ['Quinta de Tilcoco', 'Quinta de Tilcoco', "Libertador General Bernardo O'Higgins", 'Cachapoal', 0.047] ,
                ['Cunco', 'Cunco', 'La Araucanía', 'Cautín', 0.047] ,
                ['Isla de Pascua', 'Hanga roa', 'Valparaíso', 'Isla de Pascua', 0.047] ,
                ['Dalcahue', 'Dalcahue', 'Los Lagos', 'Chiloé', 0.047] ,
                ['Longaví', 'Longaví', 'Maule', 'Linares', 0.047] ,
                ['Futrono', 'Futrono', 'Los Ríos', 'Ranco', 0.047] ,
                ['Huasco', 'Huasco', 'Atacama', 'Huasco', 0.046] ,
                ['Maule', 'Maule', 'Maule', 'Talca', 0.046] ,
                ['Buin', 'Alto Jahuel', 'Metropolitana de Santiago', 'Maipo', 0.046] ,
                ['Mostazal', 'La Punta', "Libertador General Bernardo O'Higgins", 'Cachapoal', 0.046] ,
                ['El Tabo', 'El Tabo', 'Valparaíso', 'San Antonio', 0.046] ,
                ['Río Negro', 'Río Negro', 'Los Lagos', 'Osorno', 0.046] ,
                ['Colbún', 'Colbún', 'Maule', 'Linares', 0.045] ,
                ['Putaendo', 'Putaendo', 'Valparaíso', 'San Felipe de Aconcagua', 0.044] ,
                ['Codegua', 'Codegua', "Libertador General Bernardo O'Higgins", 'Cachapoal', 0.044] ,
                ['Cabrero', 'Monte Águila', 'Biobío', 'Biobío', 0.043] ,
                ['Monte Patria', 'Monte Patria', 'Coquimbo', 'Limarí', 0.043] ,
                ['Renaico', 'Renaico', 'La Araucanía', 'Malleco', 0.043] ,
                ['Romeral', 'Romeral', 'Maule', 'Curicó', 0.043] ,
                ['Vilcún', 'Vilcún', 'La Araucanía', 'Cautín', 0.042] ,
                ['San José de Maipo', 'San José de Maipo', 'Metropolitana de Santiago', 'Cordillera', 0.041] ,
                ['Monte Patria', 'El Palqui', 'Coquimbo', 'Limarí', 0.041] ,
                ['Santo Domingo', 'Santo Domingo', 'Valparaíso', 'San Antonio', 0.04] ,
                ['Chépica', 'Chépica', "Libertador General Bernardo O'Higgins", 'Colchagua', 0.04] ,
                ['Hospital', 'Paine', 'Metropolitana de Santiago', 'Maipo', 0.04] ,
                ['Diego de Almagro', 'El Salvador', 'Atacama', 'Chañaral', 0.04] ,
                ['Porvenir', 'Porvenir', 'Magallanes y de la Antártica Chilena', 'Tierra del Fuego', 0.039] ,
                ['Combarbalá', 'Combarbalá', 'Coquimbo', 'Limarí', 0.039] ,
                ['Hualañé', 'Hualañé', 'Maule', 'Curicó', 0.038] ,
                ['Punitaqui', 'Punitaqui', 'Coquimbo', 'Limarí', 0.037] ,
                ['Cajón', 'Vilcún', 'La Araucanía', 'Cautín', 0.037] ,
                ['Chonchi', 'Chonchi', 'Los Lagos', 'Chiloé', 0.037] ,
                ['Pichidegua', 'Pichidegua', "Libertador General Bernardo O'Higgins", 'Cachapoal', 0.037] ,
                ['Coquimbo', 'Tongoy', 'Coquimbo', 'Elqui', 0.036] ,
                ['Tiltil', 'Tiltil', 'Metropolitana de Santiago', 'Chacabuco', 0.036] ,
                ['Rauco', 'Rauco', 'Maule', 'Curicó', 0.036] ,
                ['Retiro', 'Retiro', 'Maule', 'Linares', 0.036] ,
                ['El Tabo', 'Las Cruces (San Antonio)', 'Valparaíso', 'San Antonio', 0.036] ,
                ['Coltauco', 'Coltauco', "Libertador General Bernardo O'Higgins", 'Cachapoal', 0.036] ,
                ['Freire', 'Freire', 'La Araucanía', 'Cautín', 0.036] ,
                ['Olivar', 'Gultro (Rancagua)', "Libertador General Bernardo O'Higgins", 'Cachapoal', 0.036] ,
                ['San Pedro de Atacama', 'San Pedro de Atacama', 'Antofagasta', 'El Loa', 0.035] ,
                ['Melipilla', 'Bollenar', 'Metropolitana de Santiago', 'Melipilla', 0.035] ,
                ['Peralillo', 'Peralillo', "Libertador General Bernardo O'Higgins", 'Colchagua', 0.035] ,
                ['Puchuncaví', 'Puchuncaví', 'Valparaíso', 'Valparaíso', 0.035] ,
                ['Arauco', 'Laraquete', 'Biobío', 'Arauco', 0.033] ,
                ['Chile Chico', 'Chile Chico', 'Aysén del General Carlos Ibáñez del Campo', 'General Carrera', 0.021] ,
                ['Cochrane', 'Cochrane', 'Aysén del General Carlos Ibáñez del Campo', 'Capitán Prat', 0.018] ,
                ['Cabo de Hornos', 'Puerto Williams', 'Magallanes y de la Antártica Chilena', 'Antártica Chilena', 0.012] ,
                ['Putre', 'Putre', 'Arica y Parinacota', 'Parinacota', 0.011] ,
                ['Chaitén', 'Chaitén', 'Los Lagos', 'Palena', 0.011]]

#Estado Civil, Probabilidad (Basado en probabilidades obtenidas en estudio realizado en el 2020)
estado_civil = [["Casado/a", 31],["Conviviente Civil", 3],["Divorciado/a", 7],["Viudo/a", 6], ["Soltero/a", 53]]

import random
from datetime import datetime
import csv

def aplicar_probabilidades(lista,  indice_probabilidad):
    aux = []
    for i in lista:
        aux.extend([i]*round(i[indice_probabilidad]*100))
    return aux

#Duplica las distintas localizaciones dentro del arreglo de acuerdo a su probabilidad 
localizacion = aplicar_probabilidades(localizacion, 4)
estado_civil = aplicar_probabilidades(estado_civil, 1)


numero_datos = int(input("INGRESE NUMERO DE DATOS A GENERAR: "))
try:
    archivo   = open('personas.csv',"w", newline="", encoding='utf-8')
    escritura = csv.writer(archivo, delimiter=",", quotechar=",", quoting=csv.QUOTE_MINIMAL)

    escritura.writerow(["nombre", "sexo", "fecha_nacimiento", "estado_civil", "comuna",
                        "ciudad", "región", "provincia", "numero_hijos"])

    for i in range(0,numero_datos):
        sexo = random.randint(0,1)
        nombre = ""

        #Se crea un nombre
        if sexo == 0:
            while True:
                primer_nombre  = random.randint(0,len(hombres_nombres)-1)
                segundo_nombre = random.randint(0,len(hombres_nombres)-1)
                nombre         = "%s %s"%(hombres_nombres[primer_nombre].upper(),hombres_nombres[segundo_nombre].upper())

                if(primer_nombre != segundo_nombre):
                    break
        else:
            while True:
                primer_nombre  = random.randint(0,len(mujeres_nombres)-1)
                segundo_nombre = random.randint(0,len(mujeres_nombres)-1)
                nombre         = "%s %s"%(mujeres_nombres[primer_nombre].upper(),mujeres_nombres[segundo_nombre].upper())

                if(primer_nombre != segundo_nombre):
                    break

        while True:
            primer_apellido  = random.randint(0,len(apellidos)-1)
            segundo_apellido = random.randint(0,len(apellidos)-1)
            apellido         = "%s %s"%(apellidos[primer_apellido].upper(),apellidos[segundo_apellido].upper())

            if(primer_apellido != segundo_apellido):
                nombre += " %s"%apellido
                break

        sexo = "MASCULINO" if sexo == 0 else "FEMENINO"

        #Seleccion de estado civil y ciudad
        aux_estado_civil = random.choice(estado_civil)
        aux_localizacion = random.choice(localizacion)

        #Rango de fechas entre las cuales se elige una
        inicio = datetime(1985, 1, 1)
        final =  datetime(2023, 1, 1)

        fecha_nacimiento = inicio + (final - inicio) * random.random()

        #Si la persona es mayor a 18 años se ejecuta un random entre 0 a 4 hijos. Si es menor seran 0
        #Ademas de que si no es mayor de 18 el estado civil sera "Soltero/a".
        numero_hijos     = random.randint(0,4) if (datetime.now()- fecha_nacimiento).days>6570 else 0
        aux_estado_civil = aux_estado_civil if (datetime.now()- fecha_nacimiento).days>6570 else ["Soltero/a"]

        escritura.writerow([nombre, sexo, fecha_nacimiento.date(), aux_estado_civil[0], aux_localizacion[0], aux_localizacion[1],
                            aux_localizacion[2], aux_localizacion[3], numero_hijos])

    archivo.close()

except:
    print("NO HA INGRESADO UN NUMERO VALIDO...")
