
#Datos utilizados para rellenar información
hombres_nombres  = ['Adel', 'Adonis', 'Ajaz', 'Akos', 'Aldo', 'Amets', 'Amaro',
                    'Aquiles', 'Algimantas', 'Alpidio', 'Amrane', 'Anish', 'Arián',
                    'Ayun', 'Azariel', 'Bagrat', 'Bencomo', 'Bertino', 'Candi',
                    'Cesc', 'Cirino', 'Crisólogo', 'Cruz', 'Danilo', 'Dareck',
                    'Dariel', 'Darin', 'Delmiro', 'Damen', 'Dilan', 'Dipa',
                    'Doménico', 'Drago', 'Edivaldo', 'Elvis', 'Elyan', 'Emeric',
                    'Engracio', 'Ensa', 'Eñaut', 'Eleazar', 'Eros', 'Eufemio',
                    'Feiyang', 'Fiorenzo', 'Foudil', 'Galo', 'Gastón', 'Giulio',
                    'Gautam', 'Gentil', 'Gianni', 'Gianluca', 'Giorgio', 'Gourav',
                    'Grober', 'Guido', 'Guifre', 'Guim', 'Hermes', 'Inge', 'Irai',
                    'Iraitz', 'Iyad', 'Iyán', 'Jeremías', 'Joao', 'Jun', 'Khaled',
                    'Leónidas', 'Lier', 'Lionel', 'Lisandro', 'Lucián', 'Mael',
                    'Misael', 'Moad', 'Munir', 'Nael', 'Najim', 'Neo', 'Neil',
                    'Nikita', 'Nilo', 'Otto', 'Pep', 'Policarpo', 'Radu', 'Ramsés',
                    'Rómulo', 'Roy', 'Severo', 'Sidi', 'Simeón', 'Taha', 'Tao',
                    'Vadim', 'Vincenzo', 'Zaid', 'Zigor', 'Zouhair', 'Hugo', 'Mateo',
                    'Martín', 'Lucas', 'Leo', 'Daniel', 'Alejandro', 'Manuel',
                    'Pablo', 'Álvaro', 'Adrián', 'Enzo', 'Mario', 'Diego', 'David',
                    'Oliver', 'Marcos', 'Thiago', 'Marco', 'Álex', 'Javier', 'Izan',
                    'Bruno', 'Miguel', 'Antonio', 'Gonzalo', 'Liam', 'Gael', 'Marc',
                    'Carlos', 'Juan', 'Ángel', 'Dylan', 'Nicolás', 'José', 'Sergio',
                    'Gabriel', 'Luca', 'Jorge', 'Darío', 'Íker', 'Samuel', 'Eric',
                    'Adam', 'Héctor', 'Francisco', 'Rodrigo', 'Jesús', 'Erik', 'Amir',
                    'Jaime', 'Ian', 'Rubén', 'Aarón', 'Iván', 'Pau', 'Víctor',
                    'Guillermo', 'Luis', 'Mohamed', 'Pedro', 'Julen', 'Unai', 'Rafael',
                    'Santiago', 'Saúl', 'Alberto', 'Noah', 'Aitor', 'Joel', 'Nil', 'Jan',
                    'Pol', 'Raúl', 'Matías', 'Martí', 'Fernando', 'Andrés', 'Rayan',
                    'Alonso', 'Ismael', 'Asier', 'Biel', 'Ander', 'Aleix', 'Axel', 'Alan',
                    'Ignacio', 'Fabio', 'Neizan', 'Jon', 'Teo', 'Isaac', 'Arnau', 'Luka',
                    'Max', 'Imran', 'Youssef', 'Anas', 'Elías', 'Abaigar', 'Adei', 'Adur',
                    'Adiran', 'Aimar', 'Aitor', 'Andoni', 'Ander', 'Antxon', 'Amets',
                    'Aratz', 'Argi', 'Aritz', 'Asier', 'Balkoe', 'Baltz', 'Bazkoare',
                    'Beltso', 'Bernat', 'Beñat', 'Bikendi', 'Biktor', 'Bizen', 'Dabi',
                    'Dari', 'Damen', 'Diagur', 'Dunixi', 'Eako', 'Eder', 'Edorta',
                    'Edur', 'Eki', 'Ekaitz', 'Eladi', 'Elixi', 'Eloi', 'Emiri', 'Eneko',
                    'Endrike', 'Eritz', 'Etor', 'Euken', 'Ferran', 'Frantzisko', 'Ganiz',
                    'Gari', 'Gentzen', 'Gergori', 'Gilem', 'Gizon', 'Goiznabar',
                    'Gontzal', 'Gorka', 'Grazian', 'Guren', 'Haize', 'Haran', 'Haritz',
                    'Heiko', 'Hodei', 'Ibai', 'Ibar', 'Igon', 'Igor', 'Iker', 'Imanol',
                    'Iñaki', 'Ipar', 'Irai', 'Iren', 'Izan', 'Izei', 'Jon', 'Jeino',
                    'Joritz', 'Josu', 'Julen', 'Jurgi', 'Kai', 'Kasi', 'Kauldi', 'Kutun',
                    'Lain', 'Luken', 'Maide', 'Mairu', 'Maren', 'Markel', 'Martitz',
                    'Mikel', 'Negu', 'Neketi', 'Nikanor', 'Odei', 'Oier', 'Oihan',
                    'Orentzi', 'Orixe', 'Ortzadar', 'Ostertz', 'Paken', 'Patxi', 'Roke',
                    'Sanduru', 'Semenko', 'Sendoa', 'Silban', 'Sukil', 'Todor', 'Txarles',
                    'Ugutz', 'Uhaitz', 'Unai', 'Untzalu', 'Urtzi', 'Uztai', 'Xabier',
                    'Zuhaitz', 'Zuri', 'Zuzen', 'Adolf', 'Adrià', 'Agustí', 'Alberic',
                    'Aleix', 'Àlvar', 'Amadeu', 'Andreu', 'Aran', 'Ariel', 'Arnald',
                    'Arnau', 'Artur', 'Bernabe', 'Bernat', 'Biel', 'Blai', 'Carles',
                    'Cesc', 'Climen', 'Constantí', 'Cosme', 'Cristòfol', 'Domènech',
                    'Doroteu', 'Eduard', 'Elies', 'Eloi', 'Elpidi', 'Enric', 'Ernest',
                    'Estanislau', 'Esteve', 'Eugeni', 'Eusevi', 'Feliu', 'Ferran',
                    'Ferrer', 'Fredreric', 'Genari', 'Gener', 'Genis', 'Gonçal', 'Guifré',
                    'Guillem', 'Guiu', 'Honorat', 'Hospici', 'Ignasi', 'Isidre', 'Jacint',
                    'Jan', 'Jaume', 'Joaquín', 'Jonatan', 'Jordi', 'Leopold', 'Lluc',
                    'Marc', 'Marcel', 'Martí', 'Mateu', 'Maurici', 'Màxim', 'Medir',
                    'Moisès', 'Nadal', 'Nicolau', 'Nil', 'Oriol', 'Osvald', 'Ovidi',
                    'Pacomi', 'Pelai', 'Pere', 'Pol', 'Prosper', 'Rafel', 'Raimon',
                    'Raül', 'Ricard', 'Robert', 'Roc', 'Roderic', 'Roger', 'Sanc',
                    'Sàndal', 'Serni', 'Simó', 'Thiago', 'Valentí', 'Vicenç', 'Víctor',
                    'Virgili', 'Xavi', 'Xavier', 'Zoel', 'Agostiño', 'Airas', 'Alberte',
                    'Aleixo', 'Aldán', 'Alexandre', 'Amaro', 'Amil', 'André', 'Anselmo',
                    'Antón', 'Antoín', 'Antoíño', 'Ánxelo', 'Anxo', 'Anxos', 'Artai',
                    'Artur', 'Arximiro', 'Aurelio', 'Basilio', 'Benedito', 'Bento',
                    'Benvito', 'Benxamín', 'Bernal', 'Bernaldo', 'Bernardiño', 'Bieito',
                    'Boaventura', 'Brais', 'Breixo', 'Breogán', 'Brigo', 'Bruno',
                    'Caetano', 'Calisto', 'Calros', 'Camilo', 'Cibrán', 'Cilistro',
                    'Ciriaco', 'Clemenzo', 'Clodio', 'Cosme', 'Cristovo', 'Davide',
                    'Diogo', 'Domingos', 'Duarte', 'Eloy', 'Estevo', 'Euloxio', 'Eutelo',
                    'Euxenio', 'Exidio', 'Fernán', 'Fidel', 'Filipe', 'Firmino', 'Fiz',
                    'Frederico', 'Froitoso', 'Gasparo', 'Goio', 'Hixinio', 'Iago',
                    'Lois', 'Luar', 'Luís', 'Manoel', 'Martiño', 'Odón', 'Pascoal',
                    'Payo', 'Peio', 'Pello', 'Peru', 'Quentin', 'Roi', 'Roxelio', 'Rui',
                    'Tadeu', 'Uxío', 'Vicenzo', 'Virxilio', 'Xabier', 'Xacinto',
                    'Xacobe', 'Xacobo', 'Xaime', 'Xan', 'Xandro', 'Xaneiro', 'Xandre',
                    'Xaquin', 'Xenaro', 'Xeraldo', 'Xerardo', 'Xermán', 'Xesus', 'Xián',
                    'Xoán', 'Xoel', 'Xorxe', 'Xosé', 'Xurxo']
                    
mujeres_nombres  = ['Adara', 'Agata', 'Agripina', 'Ainhara', 'Aixa', 'Alegría',
                    'Alia', 'Alla', 'América', 'Aminata', 'Amor', 'Anahí', 'Ania',
                    'Aquilina', 'Ariadne', 'Arya', 'Asia', 'Atenea', 'Bella',
                    'Benilde', 'Camino', 'Carmina', 'Casandra', 'Celina', 'Chaymae',
                    'Clemencia', 'Cora', 'Cruz', 'Custodia', 'Dalila', 'Danae',
                    'Dania', 'Demetria', 'Denise', 'Doina', 'Dominica', 'Dorina',
                    'Doris', 'Duna', 'Elaia', 'Elida', 'Enma', 'Erundina', 'Etelvina',
                    'Evelia', 'Evelin', 'Fatma', 'Federica', 'Flavia', 'Florina',
                    'Gadea', 'Griselda', 'Guacimara', 'Guiomar', 'Hasna', 'Indara',
                    'Inna', 'Iraide', 'Irantzu', 'Ivette', 'Jade', 'Johana', 'Juncal',
                    'Kira', 'Larisa', 'Laureana', 'Leia', 'Lena', 'Leocadia', 'Libe',
                    'Lilia', 'Linda', 'Lisa', 'Liudmila', 'Livia', 'Lluna', 'Luana',
                    'Lucinda', 'Mabel', 'Manar', 'Mariama', 'Marianela', 'Nadine',
                    'Naila', 'Nawal', 'Nazareth', 'Nelly', 'Noah', 'Norah', 'Penélope',
                    'Remei', 'Rosalba', 'Sabah', 'Safia', 'Saliha', 'Saloua', 'Sana',
                    'Sanaa', 'Severina', 'Silvina', 'Talia', 'Tasnim', 'Telma', 'Valle',
                    'Ximena', 'Xiomara', 'Yadira', 'Yamila', 'Yesenia', 'Yuliya',
                    'Yumara', 'Zakia', 'Lucía', 'Sofía', 'Martina', 'María', 'Julia',
                    'Paula', 'Valeria', 'Emma', 'Daniela', 'Carla', 'Alba', 'Noa',
                    'Alma', 'Sara', 'Carmen', 'Vega', 'Lara', 'Mia', 'Valentina',
                    'Olivia', 'Claudia', 'Jimena', 'Lola', 'Chloe', 'Aitana', 'Abril',
                    'Ana', 'Laia', 'Triana', 'Candela', 'Alejandra', 'Elena', 'Vera',
                    'Manuela', 'Adriana', 'Inés', 'Marta', 'Carlota', 'Irene',
                    'Victoria', 'Blanca', 'Marina', 'Laura', 'Rocío', 'Alicia',
                    'Clara', 'Nora', 'Lia', 'Ariadna', 'Zoe', 'Amira', 'Gala', 'Celia',
                    'Leire', 'Eva', 'Ángela', 'Andrea', 'África', 'Luna', 'Ainhoa',
                    'Ainara', 'India', 'Nerea', 'Ona', 'Elsa', 'Isabel', 'Leyre',
                    'Gabriela', 'Aina', 'Cayetana', 'Iria', 'Jana', 'Mar', 'Cloe',
                    'Lina', 'Julieta', 'Adara', 'Naia', 'Iris', 'Nour', 'Mara',
                    'Helena', 'Yasmín', 'Natalia', 'Arlet', 'Diana', 'Aroa', 'Amaia',
                    'Cristina', 'Nahia', 'Isabella', 'Malak', 'Elia', 'Carolina',
                    'Berta', 'Fátima', 'Nuria', 'Azahara', 'Macarena', 'Aurora',
                    'Abantza', 'Abarne', 'Abesti', 'Adartza', 'Adirane', 'Agara',
                    'Agata', 'Agate', 'Aimara', 'Ainara', 'Aines', 'Ainhoa', 'Aintza',
                    'Aintzane.', 'Alaia', 'Alaikari', 'Alaiñe', 'Albane', 'Alda',
                    'Aliza', 'Alize', 'Alode', 'Alodi', 'Aloise', 'Amade', 'Amaia',
                    'Amane', 'Amele', 'Andoitza', 'Ane', 'Antia', 'Anuntxi', 'Arantxa',
                    'Arantza', 'Arene', 'Aretxa', 'Argia', 'Astere', 'Begoña',
                    'Dogartze', 'Domeka', 'Dunixe', 'Ederne', 'Edurne', 'Egia',
                    'Ekaitza', 'Elaia', 'Elaia', 'Elixe', 'Enara', 'Estibaliz',
                    'Eulari', 'Eztia', 'Florentzi', 'Gadea', 'Garaine', 'Gorane',
                    'Gure', 'Haizea', 'Haizeder', 'Hegoa', 'Ibarne', 'Ikerne',
                    'Ilargi', 'Iluntze', 'Iraide', 'Irune', 'Izadi', 'Jaione',
                    'Julene', 'Kaia', 'Kaiene', 'Keltse', 'Kemena', 'Laia', 'Leire',
                    'Letizia', 'Lide', 'Loredi', 'Lukene', 'Lutxi', 'Luzia', 'Maia',
                    'Maitane', 'Maite', 'Malen', 'Markele', 'Mikela', 'Milia',
                    'Mirari', 'Nagore', 'Nahia', 'Nahikari', 'Naiara', 'Naroa',
                    'Nekane', 'Nerea', 'Oihana', 'Oihane', 'Olaia', 'Paule',
                    'Polentze', 'Sabiñe', 'Santsa', 'Sarabe', 'Sua', 'Tala',
                    'Taresa', 'Uda', 'Udane', 'Udara', 'Ula', 'Urzuri', 'Yera',
                    'Zeiane', 'Zohardi', 'Zorione', 'Zumaia', 'Zuria', 'Zuzene',
                    'Abellera', 'Agnès', 'Aida', 'Aïna', 'Aisha', 'Aixa', 'Albà',
                    'Alix', 'Alma', 'Aloma', 'Anaïs', 'Àngels', 'Anna', 'Ares',
                    'Ariadna', 'Arlet', 'Aura', 'Bet', 'Beth', 'Blau', 'Cel',
                    'Cèlia', 'Chloé', 'Cira', 'Clàudia', 'Cloè', 'Consol', 'Cora',
                    'Dàlia', 'Dèlia', 'Dolça', 'Duna', 'Dúnia', 'Edna', 'Elna',
                    'Elsa', 'Emma', 'Estel', 'Etna', 'Finestres', 'Francina',
                    'Gemma', 'Gina', 'Iria', 'Ivet', 'Jana', 'Joana', 'Judit',
                    'Júlia', 'Laia', 'Lara', 'Lea', 'Lena', 'Lia', 'Lis', 'Llora',
                    'Llúcia', 'Margarida', 'Meritxell', 'Mireia', 'Montserrat',
                    'Nàdia', 'Nara', 'Neus', 'Nina', 'Nit', 'Noa', 'Nora', 'Nura',
                    'Núria', 'Ona', 'Queralt', 'Ramona', 'Remei', 'Rita', 'Roser',
                    'Sança', 'Sira', 'Socors', 'Sol', 'Soledat', 'Thaís', 'Txell',
                    'Vera', 'Vinyet', 'Xènia', 'Zoa', 'Ádega', 'Agostiña', 'Áine',
                    'Alana', 'Alborada', 'Albura', 'Alda', 'Aldana', 'Alexandra',
                    'Alexia', 'Alla', 'Alodia', 'Aloia', 'Amaina', 'Amil', 'Antela',
                    'Antía', 'Antoniña', 'Anxa', 'Ánxela', 'Ánxeles', 'Anxélica',
                    'Anxos', 'Apana', 'Aranza', 'Aránzazu', 'Arduína', 'Arxentina',
                    'Asunta', 'Aunia', 'Baia', 'Balla', 'Beata', 'Bélxica', 'Benvida',
                    'Benxamina', 'Branca', 'Brenda', 'Briana', 'Brianda', 'Brisda',
                    'Bríxida', 'Camiño', 'Candea', 'Candeloria', 'Catuxa', 'Cebreiro',
                    'Cecía', 'Cela', 'Celina', 'Celtia', 'Chorima', 'Cía', 'Cilla',
                    'Doa', 'Dubra', 'Einés', 'Elba', 'Elvia', 'Erea', 'Euxea',
                    'Euxenia', 'Evelina', 'Exeria', 'Franqueira', 'Fulxencia',
                    'Glenda', 'Hixinia', 'Icía', 'Ifixenia', 'Ilduara', 'Iria',
                    'Iría', 'Irimia', 'Lana', 'Loucia', 'Malvina', 'Maxina',
                    'Mencía', 'Minia', 'Moira', 'Mor', 'Muma', 'Muriel', 'Navia',
                    'Noela', 'Noreia', 'Roxelia', 'Roxeria', 'Sabela', 'Sarela',
                    'Tareixa', 'Ulla', 'Uxía', 'Virxilia', 'Xacinta', 'Xandra',
                    'Xaquelina', 'Xasmín', 'Xela', 'Xeloíra', 'Xema', 'Xenevra',
                    'Xenia', 'Xenoveva', 'Xenxa', 'Xiana', 'Xilda', 'Xosefa',
                    'Xudite', 'Xulia', 'Xulieta', 'Xunqueira', 'Xuventina', 'Zeltia']

apellidos        = ['González', 'Muñoz', 'Rojas', 'Díaz', 'Pérez', 'Soto',
                    'Contreras', 'Silva', 'Martínez', 'Sepúlveda', 'Morales',
                    'Rodríguez', 'López', 'Fuentes', 'Hernández', 'Torres', 'Araya',
                    'Flores', 'Espinoza', 'Valenzuela', 'Castillo', 'Tapia', 'Reyes',
                    'Gutiérrez', 'Castro', 'Pizarro', 'Álvarez', 'Vásquez', 'Sánchez',
                    'Fernández', 'Ramírez', 'Carrasco', 'Gómez', 'Cortés', 'Herrera',
                    'Núñez', 'Jara', 'Vergara', 'Rivera', 'Figueroa', 'Riquelme',
                    'García', 'Miranda', 'Bravo', 'Vera', 'Molina', 'Vega', 'Campos',
                    'Sandoval', 'Orellana', 'Cárdenas', 'Olivares', 'Alarcón',
                    'Gallardo', 'Ortiz', 'Garrido', 'Salazar', 'Guzmán', 'Henríquez',
                    'Saavedra', 'Navarro', 'Aguilera', 'Parra', 'Romero', 'Aravena',
                    'Vargas', 'Vázquez', 'Cáceres', 'Yáñez', 'Leiva', 'Escobar',
                    'Ruiz', 'Valdés', 'Vidal', 'Salinas', 'Zúñiga', 'Peña', 'Godoy',
                    'Lagos', 'Maldonado', 'Bustos', 'Medina', 'Pino', 'Palma',
                    'Moreno', 'Sanhueza', 'Carvajal', 'Navarrete', 'Sáez', 'Alvarado',
                    'Donoso', 'Poblete', 'Bustamante', 'Toro', 'Ortega', 'Venegas',
                    'Lopez', 'Mendoza', 'Farías', 'San Martín', 'Lucero', 'Sosa',
                    'Quiroga', 'Jiménez', 'Mora', 'Calderón', 'Martín', 'Alonso',
                    'Domínguez', 'Ramos']

ciudad_region    = [
                    ['Arica', ' Región de Arica y Parinacota'] ,
                    ['Iquique', ' Tarapacá'] ,
                    ['Alto Hospicio', 'Tarapacá'] ,
                    ['Pozo Almonte', 'Tarapacá'] ,
                    ['Antofagasta', ' Antofagasta'] ,
                    ['Calama', 'Antofagasta'] ,
                    ['Tocopilla', 'Antofagasta'] ,
                    ['Chuquicamata', 'Antofagasta'] ,
                    ['Taltal', 'Antofagasta'] ,
                    ['Estación Zaldívar', 'Antofagasta'] ,
                    ['Mejillones', 'Antofagasta'] ,
                    ['María Elena', 'Antofagasta'] ,
                    ['Copiapó', ' Atacama'] ,
                    ['Vallenar', 'Atacama'] ,
                    ['Caldera', 'Atacama'] ,
                    ['Chañaral', 'Atacama'] ,
                    ['El Salvador', 'Atacama'] ,
                    ['Tierra Amarilla', 'Atacama'] ,
                    ['Diego de Almagro', 'Atacama'] ,
                    ['Huasco', 'Atacama'] ,
                    ['Coquimbo', ' Coquimbo'] ,
                    ['La Serena', 'Coquimbo'] ,
                    ['Ovalle', 'Coquimbo'] ,
                    ['Illapel', 'Coquimbo'] ,
                    ['Vicuña', 'Coquimbo'] ,
                    ['Salamanca', 'Coquimbo'] ,
                    ['Los Vilos', 'Coquimbo'] ,
                    ['Andacollo', 'Coquimbo'] ,
                    ['Combarbalá', 'Coquimbo'] ,
                    ['El Palqui', 'Coquimbo'] ,
                    ['Monte Patria', 'Coquimbo'] ,
                    ['Viña del mar', ' Valparaíso'] ,
                    ['Valparaíso', 'Valparaíso'] ,
                    ['Quilpué', 'Valparaíso'] ,
                    ['Villa Alemana', 'Valparaíso'] ,
                    ['San Antonio', 'Valparaíso'] ,
                    ['Quillota', 'Valparaíso'] ,
                    ['Los Andes', 'Valparaíso'] ,
                    ['San Felipe', 'Valparaíso'] ,
                    ['La Calera', 'Valparaíso'] ,
                    ['Limache', 'Valparaíso'] ,
                    ['Concón', 'Valparaíso'] ,
                    ['Quintero', 'Valparaíso'] ,
                    ['La Ligua', 'Valparaíso'] ,
                    ['Llay-Llay', 'Valparaíso'] ,
                    ['Cartagena', 'Valparaíso'] ,
                    ['Casablanca', 'Valparaíso'] ,
                    ['Cabildo', 'Valparaíso'] ,
                    ['Placilla de Peñuelas', 'Valparaíso'] ,
                    ['La Cruz', 'Valparaíso'] ,
                    ['Olmué', 'Valparaíso'] ,
                    ['El Melón', 'Valparaíso'] ,
                    ['Nogales', 'Valparaíso'] ,
                    ['El Quisco', 'Valparaíso'] ,
                    ['Hijuelas', 'Valparaíso'] ,
                    ['San Esteban', 'Valparaíso'] ,
                    ['Putaendo', 'Valparaíso'] ,
                    ['Catemu', 'Valparaíso'] ,
                    ['Santa Maria', 'Valparaíso'] ,
                    ['Las Ventanas', 'Valparaíso'] ,
                    ['Algarrobo', 'Valparaíso'] ,
                    ['Rinconada', 'Valparaíso'] ,
                    ['Calle Larga', 'Valparaíso'] ,
                    ['Santo Domingo', 'Valparaíso'] ,
                    ['El Tabo', 'Valparaíso'] ,
                    ['Puente Alto', ' Región Metropolitana de Santiago'] ,
                    ['Maipú', 'Santiago Metropolitano'] ,
                    ['La Florida', 'Santiago Metropolitano'] ,
                    ['Las Condes', 'Santiago Metropolitano'] ,
                    ['San Bernardo', 'Santiago Metropolitano'] ,
                    ['Peñalolén', 'Santiago Metropolitano'] ,
                    ['Santiago', 'Santiago Metropolitano'] ,
                    ['Pudahuel', 'Santiago Metropolitano'] ,
                    ['La Pintana', 'Santiago Metropolitano'] ,
                    ['El Bosque', 'Santiago Metropolitano'] ,
                    ['Ñuñoa', 'Santiago Metropolitano'] ,
                    ['Cerro Navia', 'Santiago Metropolitano'] ,
                    ['Recoleta', 'Santiago Metropolitano'] ,
                    ['Renca', 'Santiago Metropolitano'] ,
                    ['Conchalí', 'Santiago Metropolitano'] ,
                    ['La Granja', 'Santiago Metropolitano'] ,
                    ['Estación Central', 'Santiago Metropolitano'] ,
                    ['Quilicura', 'Santiago Metropolitano'] ,
                    ['Providencia', 'Santiago Metropolitano'] ,
                    ['Pedro Aguirre Cerda', 'Santiago Metropolitano'] ,
                    ['Lo Espejo', 'Santiago Metropolitano'] ,
                    ['Macul', 'Santiago Metropolitano'] ,
                    ['Lo Prado', 'Santiago Metropolitano'] ,
                    ['Quinta Normal', 'Santiago Metropolitano'] ,
                    ['San Joaquín', 'Santiago Metropolitano'] ,
                    ['La Reina', 'Santiago Metropolitano'] ,
                    ['San Ramón', 'Santiago Metropolitano'] ,
                    ['La Cisterna', 'Santiago Metropolitano'] ,
                    ['Vitacura', 'Santiago Metropolitano'] ,
                    ['San Miguel', 'Santiago Metropolitano'] ,
                    ['Huechuraba', 'Santiago Metropolitano'] ,
                    ['Lo Barnechea', 'Santiago Metropolitano'] ,
                    ['Cerrillos', 'Santiago Metropolitano'] ,
                    ['Independencia', 'Santiago Metropolitano'] ,
                    ['Peñaflor', 'Santiago Metropolitano'] ,
                    ['Colina', 'Santiago Metropolitano'] ,
                    ['Melipilla', 'Santiago Metropolitano'] ,
                    ['Talagante', 'Santiago Metropolitano'] ,
                    ['Buin', 'Santiago Metropolitano'] ,
                    ['Padre Hurtado', 'Santiago Metropolitano'] ,
                    ['El Monte', 'Santiago Metropolitano'] ,
                    ['Paine', 'Santiago Metropolitano'] ,
                    ['Curacaví', 'Santiago Metropolitano'] ,
                    ['Lampa', 'Santiago Metropolitano'] ,
                    ['Isla de Maipo', 'Santiago Metropolitano'] ,
                    ['La Islita', 'Santiago Metropolitano'] ,
                    ['Bajos de San Agustín', 'Santiago Metropolitano'] ,
                    ['Hospital', 'Santiago Metropolitano'] ,
                    ['Alto Jahuel', 'Santiago Metropolitano'] ,
                    ['San José de Maipo', 'Santiago Metropolitano'] ,
                    ['Tiltil', 'Santiago Metropolitano'] ,
                    ['Pirque', 'Santiago Metropolitano'] ,
                    ['Rancagua', "O'Higgins"] ,
                    ['San Fernando', "O'Higgins"] ,
                    ['Rengo', "O'Higgins"] ,
                    ['Machalí', "O'Higgins"] ,
                    ['Graneros', "O'Higgins"] ,
                    ['San Vicente de Tagua Tagua', "O'Higgins"] ,
                    ['Santa Cruz', "O'Higgins"] ,
                    ['Chimbarongo', "O'Higgins"] ,
                    ['Mostazal', "O'Higgins"] ,
                    ['Pichilemu', "O'Higgins"] ,
                    ['Requínoa', "O'Higgins"] ,
                    ['Lo Miranda', "O'Higgins"] ,
                    ['Doñihue', "O'Higgins"] ,
                    ['Peumo', "O'Higgins"] ,
                    ['Nancagua', "O'Higgins"] ,
                    ['Las Cabras', "O'Higgins"] ,
                    ['Quinta de Tilcoco', "O'Higgins"] ,
                    ['Gultro', "O'Higgins"] ,
                    ['Codegua', "O'Higgins"] ,
                    ['Palmilla', "O'Higgins"] ,
                    ['Talca', 'Maule'] ,
                    ['Curicó', 'Maule'] ,
                    ['Linares', 'Maule'] ,
                    ['Constitución', 'Maule'] ,
                    ['Cauquenes', 'Maule'] ,
                    ['Molina', 'Maule'] ,
                    ['Parral', 'Maule'] ,
                    ['San Javier', 'Maule'] ,
                    ['San Clemente', 'Maule'] ,
                    ['Teno', 'Maule'] ,
                    ['Longaví', 'Maule'] ,
                    ['Villa Alegre', 'Maule'] ,
                    ['Hualañé', 'Maule'] ,
                    ['Concepción', 'Biobío'] ,
                    ['Talcahuano', 'Biobío'] ,
                    ['Chillán', 'Biobío'] ,
                    ['Los Angeles', 'Biobío'] ,
                    ['Coronel', 'Biobío'] ,
                    ['Hualpén', 'Biobío'] ,
                    ['Chiguayante', 'Biobío'] ,
                    ['San pedro de la paz', 'Biobío'] ,
                    ['Lota', 'Biobío'] ,
                    ['Penco', 'Biobío'] ,
                    ['A mi', 'Biobío'] ,
                    ['Curanilahue', 'Biobío'] ,
                    ['San carlos', 'Biobío'] ,
                    ['Mulchén', 'Biobío'] ,
                    ['Nacimiento', 'Biobío'] ,
                    ['Lebu', 'Biobío'] ,
                    ['Cañete', 'Biobío'] ,
                    ['Chillán Viejo', 'Biobío'] ,
                    ['Arauco', 'Biobío'] ,
                    ['La Laja', 'Biobío'] ,
                    ['Hualqui', 'Biobío'] ,
                    ['Los Álamos', 'Biobío'] ,
                    ['Cabrero', 'Biobío'] ,
                    ['Bulnes', 'Biobío'] ,
                    ['Coelemu', 'Biobío'] ,
                    ['Yungay', 'Biobío'] ,
                    ['Yumbel', 'Biobío'] ,
                    ['Quirihue', 'Biobío'] ,
                    ['Quillón', 'Biobío'] ,
                    ['Coihueco', 'Biobío'] ,
                    ['Santa juana', 'Biobío'] ,
                    ['Santa Bárbara', 'Biobío'] ,
                    ['Huépil', 'Biobío'] ,
                    ['Monte Águila', 'Biobío'] ,
                    ['San Rosendo', 'Biobío'] ,
                    ['Temuco', 'Araucanía'] ,
                    ['Angol', 'Araucanía'] ,
                    ['Padre Las Casas', 'Araucanía'] ,
                    ['Villarrica', 'Araucanía'] ,
                    ['Victoria', 'Araucanía'] ,
                    ['Lautaro', 'Araucanía'] ,
                    ['Nueva Imperial', 'Araucanía'] ,
                    ['Collipulli', 'Araucanía'] ,
                    ['Loncoche', 'Araucanía'] ,
                    ['Traiguén', 'Araucanía'] ,
                    ['Pucón', 'Araucanía'] ,
                    ['Pitrufquén', 'Araucanía'] ,
                    ['Curacautín', 'Araucanía'] ,
                    ['Carahue', 'Araucanía'] ,
                    ['Gorbea', 'Araucanía'] ,
                    ['Purén', 'Araucanía'] ,
                    ['Cunco', 'Araucanía'] ,
                    ['Labranza', 'Araucanía'] ,
                    ['Freire', 'Araucanía'] ,
                    ['Renaico', 'Araucanía'] ,
                    ['Valdivia', 'Los Ríos'] ,
                    ['La Unión', 'Los Ríos'] ,
                    ['Río Bueno', 'Los Ríos'] ,
                    ['Panguipulli', 'Los Ríos'] ,
                    ['Paillaco', 'Los Ríos'] ,
                    ['Los lagos', 'Los Ríos'] ,
                    ['Lanco', 'Los Ríos'] ,
                    ['Mariquina', 'Los Ríos'] ,
                    ['Futrono', 'Los Ríos'] ,
                    ['Puerto Montt', 'Los lagos'] ,
                    ['Osorno', 'Los lagos'] ,
                    ['Castro', 'Los lagos'] ,
                    ['Ancud', 'Los lagos'] ,
                    ['Puerto Varas', 'Los lagos'] ,
                    ['Quellón', 'Los lagos'] ,
                    ['Calbuco', 'Los lagos'] ,
                    ['Purranque', 'Los lagos'] ,
                    ['Llanquihue', 'Los lagos'] ,
                    ['Frutillar', 'Los lagos'] ,
                    ['Río Negro', 'Los lagos'] ,
                    ['Fresia', 'Los lagos'] ,
                    ['Los Muermos', 'Los lagos'] ,
                    ['Coyhaique', 'Aysén'] ,
                    ['Puerto Aysén', 'Aysén'] ,
                    ['Punta Arenas', 'Magallanes'] ,
                    ['Puerto Natales', 'Magallanes']]

estados_civil     = ["Casado(a)","Conviviente","Anulado(a)","Separado de unión legal",
                    "Separado(a) de unión de hecho", "Viudo(a)", "Soltero(a)"]

import random
from datetime import datetime
import csv

archivo = open('personas.csv',"w", newline="", encoding='utf-8')
escritura = csv.writer(archivo, delimiter=",", quotechar=",",
                       quoting=csv.QUOTE_MINIMAL)
escritura.writerow(["nombre", "sexo", "fecha_nacimiento", "estado_civil",
                    "ciudad", "region", "numero_hijos"])

try:
    numero_datos = int(input("INGRESE NUMERO DE DATOS A GENERAR: "))
    for i in range(0,numero_datos):
        sexo = random.randint(0,1)
        nombre = ""

        #Se crea un nombre
        if sexo == 0:
            while True:
                primer_nombre  = random.randint(0,len(hombres_nombres)-1)
                segundo_nombre = random.randint(0,len(hombres_nombres)-1)
                nombre         = "%s %s"%(hombres_nombres[primer_nombre].upper(),hombres_nombres[segundo_nombre].upper())

                if(primer_nombre != segundo_nombre):
                    break
        else:
            while True:
                primer_nombre  = random.randint(0,len(mujeres_nombres)-1)
                segundo_nombre = random.randint(0,len(mujeres_nombres)-1)
                nombre         = "%s %s"%(mujeres_nombres[primer_nombre].upper(),mujeres_nombres[segundo_nombre].upper())

                if(primer_nombre != segundo_nombre):
                    break

        while True:
            primer_apellido  = random.randint(0,len(apellidos)-1)
            segundo_apellido = random.randint(0,len(apellidos)-1)
            apellido         = "%s %s"%(apellidos[primer_apellido].upper(),apellidos[segundo_apellido].upper())

            if(primer_apellido != segundo_apellido):
                nombre += " %s"%apellido
                break

        sexo = "MASCULINO" if sexo == 0 else "FEMENINO"
        estado_civil = random.choice(estados_civil)

        #Rango de fechas entre las cuales se elige una
        inicio = datetime(1985, 1, 1)
        final =  datetime(2023, 1, 1)

        fecha_nacimiento = (inicio + (final - inicio) * random.random()).date()
        ciudad,region    = random.choice(ciudad_region)

        #Numero de hijos
        numero_hijos = random.randint(0,4)
        escritura.writerow([nombre, sexo, fecha_nacimiento, estado_civil, ciudad, region, numero_hijos])

    archivo.close()

except:
    print("NO HA INGRESADO UN NUMERO VALIDO...")
